### ISSUE TITLE
Fix header when navigating in past events

### ISSUE THREAD

**Issue by chrisjwelly** [nuansa-cp/gapura#12]
When in past_events page, the header underlines 'Home' instead of 'Past NUANSA' 
![](https://i.imgur.com/5mnrigP.png)

**Comment by stevenwjy** [comment]
Temporarily solved with #15. 
@infinitelooped, perhaps can add helper to detect current controller/section to determine the menu that should be underlined on header?

**Comment by stevenwjy** [comment]
As of now, almost solved this issue in #38
