### ISSUE TITLE
Fix navigation between pages

### ISSUE THREAD

**Issue by chrisjwelly** [nuansa-cp/gapura#13]
As a user, when I press a button on the header, I would expect to be brought to a new page and to the top of the page. Currently, I will be brought to be the top of the page only if I were originally on top of the page.

For example: If I am in the middle of the landing page as pictured here:
![](https://imgur.com/FlI7RvN.png)

Pressing 'Past NUANSA' would bring me here, which is not the top of the page but a corresponding location from the first page. 
![](https://imgur.com/1xBCBaz.png)

The reverse is true. If I were at the same Past NUANSA page, and I were to press 'Home' or 'About Us', it would redirect me to the same location as the first picture, although the route for 'About Us' should have specified that I will be automatically brought to the About section of the page.
I am using Firefox to run the local server.

-----
Update:
On the mobile version, there is an additional issue regarding this associated with zooming.
Here, I am zoomed in a little bit
![](https://imgur.com/0ysTXOn.png)

And when I press 'Past NUANSA', I am redirected to the corresponding page (not the top of the page), AND my screen remains zoomed in.
![](https://imgur.com/FCZzGBL.png)

**Comment by chrisjwelly** [comment]
Updated my comment to include feedback for the mobile version.

**Comment by stevenwjy** [comment]
The issue regarding start point when trying to load the web through link has been resolved in #26, now it always points to the top of the page.

For the zoom issue, I just realised about it and am currently trying to resolve this problem

**Comment by stevenwjy** [comment]
Resolved in #23
