### ISSUE TITLE
Route to home when clicking logo on the header

### ISSUE THREAD

**Issue by chrisjwelly** [nuansa-cp/gapura#16]
As a user, I would expect to be redirected to the homepage when clicking the NUANSA logo on the upper left-hand corner. Currently, such routing has not been implemented yet. 

This issue is not very problematic for the web version (though an implementation would be nice), but it is more obvious when navigating in the mobile version. As the usual 'home' button has to be accessed by first pressing the menu tab, I think a user would prefer just clicking on the NUANSA logo directly on the mobile version to be redirected back to the home page.

**Comment by stevenwjy** [comment]
Yeah, there is currently an issue with the javascript code. Hence, if you put the link to home and it is clicked, sometimes the video button and text on the banner will disappear. I think that we will need to resolve that problem first.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
