### ISSUE TITLE
Update contents of the website

### ISSUE THREAD

**Issue by russelbradley** [nuansa-cp/gapura#19]
Hi Steven and IT team. 

I would be posting a few content-related updates from the producers here. I would try not to edit any of your codes. 

I'll try my best to update you with the latest/correct content before the proposed launch this Sunday.
 
Thanks
-Russel

**Comment by russelbradley** [comment]
gapura/app/views/welcome/_about.html.erb
gapura/app/views/layouts/_footer.html.erb

Change:
"NUANSA is an annual arts and cultural event by a group of Indonesian students in NUS. It aims to promote the rich and diverse cultures of Indonesia."

To:
"NUANSA is a cultural production group based in the National University of Singapore. Through contemporary musical theatre, we attempt to showcase the beauty and diversity of Indonesian cultures. We consistently endeavor to bring the audience through an immersive journey by ensuring the cultural authenticity and artistic integrity of our shows and events. Since our inception in 2008, we have grown from strength to strength: from a small independent Indonesian performance group to one of the biggest student productions in Singapore, featuring a large and diverse community from different nationalities."

**Comment by russelbradley** [comment]
gapura/app/views/welcome/_about.html.erb
gapura/app/views/welcome/_intro.html.erb

I think we can remove the "When" & "Where" and just put the information there. (for _about.html.erb only)

The correct information is:
University Cultural Centre Theatre
Monday, 28 October 2019 (Public Holiday)

(use exact wording)

Please include a space to enter our show times, which we don't have at this moment. Hans will keep you updated in this. We won't have this by the launch date.

**Comment by russelbradley** [comment]
gapura/app/views/welcome/_intro.html.erb

I'll try to ask Hans & Creative for a compilation video instead of using Galigo video. This is not urgent

**Comment by stevenwjy** [comment]
Solved by #20
